version: "3.4"

services:
  proactive_app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: proactive_app
    container_name: proactive_app
    ports:
      - "8000:8000"
    networks:
      - proactive_app_network
    env_file:
      - proactive.env

  proactive_webserver:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    image: proactive_web
    container_name: proactive_webserver
    ports:
      - "8080:8080"
    networks:
      - proactive_app_network

  postgres:
    image: postgres:13.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: proactive
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - proactive_app_network

networks:
  proactive_app_network:
    driver: bridge
